
# Memory Optimization Configuration
# Generated by performance optimizer

MEMORY_OPTIMIZATION_CONFIG = {
  "gc_threshold": 1000,
  "memory_limit_mb": 2048,
  "cleanup_interval": 300,
  "max_objects_per_request": 1000
}

# Memory management settings
GC_THRESHOLD = 1000
MEMORY_LIMIT_MB = 2048
CLEANUP_INTERVAL = 300
MAX_OBJECTS_PER_REQUEST = 1000
