
# Optimized Database Configuration
# Generated by performance optimizer

OPTIMIZED_DATABASE_CONFIG = {
  "pool_size": 20,
  "max_overflow": 40,
  "pool_pre_ping": true,
  "pool_recycle": 3600,
  "echo": false,
  "future": true
}

# Connection pool settings
POOL_SIZE = 20
MAX_OVERFLOW = 40
POOL_PRE_PING = True
POOL_RECYCLE = 3600
